export const FETCH_ABOUTDATA_REQUEST ='FETCH_ABOUTDATA_REQUEST'
export const FETCH_ABOUTDATA_SUCCESS = 'FETCH_ABOUTDATA_SUCCESS'
export const FETCH_ABOUTDATA_FAILURE = 'FETCH_ABOUTDATA_FAILURE'
export const FETCH_ABOUT_TOKEN ='FETCH_ABOUT_TOKEN'