export const FETCH_SPECDATA_REQUEST ='FETCH_SPECDATA_REQUEST'
export const FETCH_SPECDATA_SUCCESS = 'FETCH_SPECDATA_SUCCESS'
export const FETCH_SPECDATA_FAILURE = 'FETCH_SPECDATA_FAILURE'
export const FETCH_ABOUT_TOKEN ='FETCH_ABOUT_TOKEN'